import { inventoryApiUrl, readApiError, requireStaffAccess } from "@/lib/staff-access"
import { addResponseAction, approveReturnAction, createDispatchAction, createGrnAction, createPickingAction, createPoAction, createRequisitionAction, createReturnAction, createRfqAction, decidePoAction, decideRequisitionAction, deliverAction, inspectReturnAction, postDispatchAction, postGrnAction, receiveReturnAction, sendPoAction, submitRequisitionAction } from "./actions"

type Row={id:string;reference:string;status:string;[key:string]:unknown}; type Option={id:string;name?:string;sku?:string;unit?:string;product?:{name:string}}; type Data={requisitions:Row[];rfqs:Row[];purchaseOrders:Row[];receipts:Row[];salesOrders:Row[];pickingLists:Row[];dispatches:Row[];returns:Row[];variants:Option[];locations:Option[];suppliers:Option[]}
const panel="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"; const input="mt-1 h-10 w-full rounded-xl border border-slate-200 px-3 text-sm"; const button="min-h-10 rounded-xl bg-[#0a2540] px-4 py-2 text-sm font-semibold text-white hover:bg-emerald-700"; const label="text-xs font-semibold uppercase tracking-wide text-slate-600"
const Field=({name,title,type="text",value}:{name:string;title:string;type?:string;value?:string|number})=><label className={label}>{title}<input className={input} name={name} type={type} defaultValue={value} min={type==="number"?0:undefined} required/></label>
const Badge=({v}:{v:string})=><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{v.replaceAll("_"," ")}</span>
const arr=<T,>(value:unknown)=>Array.isArray(value)?value as T[]:[]

export default async function FulfilmentPage({searchParams}:{searchParams:Promise<{error?:string;saved?:string}>}){
 const {accessToken}=await requireStaffAccess("/fulfilment"); const res=await fetch(`${inventoryApiUrl}/fulfilment-operations/overview`,{headers:{Authorization:`Bearer ${accessToken}`},cache:"no-store"}); if(!res.ok)throw new Error(await readApiError(res)); const d=await res.json() as Data; const q=await searchParams
 return <main className="mx-auto max-w-[1500px] space-y-8 px-4 py-8 sm:px-6"><header><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-700">Phase 3 operations</p><h1 className="mt-2 text-3xl font-bold sm:text-4xl">Purchase, receive, dispatch and resolve returns</h1><p className="mt-2 text-slate-600">Every stock movement is posted through a connected business document and ledger transaction.</p></header>{q.error&&<p className="rounded-xl bg-red-50 p-4 text-red-700">{q.error}</p>}{q.saved&&<p className="rounded-xl bg-emerald-50 p-4 text-emerald-700">Operation saved.</p>}
 <section className="grid gap-3 sm:grid-cols-4">{[["Requisitions",d.requisitions.length],["Purchase orders",d.purchaseOrders.length],["Dispatches",d.dispatches.length],["Returns",d.returns.length]].map(x=><div className={panel} key={String(x[0])}><p className="text-sm text-slate-500">{x[0]}</p><b className="text-3xl">{x[1]}</b></div>)}</section>
 <section className={panel}><h2 className="text-xl font-bold">New purchase requisition</h2><form action={createRequisitionAction} className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className={label}>Variant<select className={input} name="variantId">{d.variants.map(v=><option value={v.id} key={v.id}>{v.product?.name} / {v.sku}</option>)}</select></label><label className={label}>Target location<select className={input} name="targetLocationId">{d.locations.map(v=><option value={v.id} key={v.id}>{v.name}</option>)}</select></label><Field name="quantity" title="Quantity" type="number" value={1}/><Field name="unitCode" title="Unit" value="unit"/><Field name="reason" title="Business reason" value="Replenish approved project stock"/><Field name="requiredBy" title="Required by" type="date"/><button className={`${button} self-end`}>Create draft</button></form></section>
 <Block title="Purchase requisitions">{d.requisitions.map(r=><Card row={r} key={r.id}>{r.status==="DRAFT"&&<Simple action={submitRequisitionAction} id={r.id} text="Submit"/>}{r.status==="SUBMITTED"&&<Decision action={decideRequisitionAction} id={r.id}/>} {r.status==="APPROVED"&&<form action={createRfqAction} className="mt-3 flex gap-2"><input type="hidden" name="id" value={r.id}/><input className={input} name="responseDueAt" type="datetime-local" required/><button className={button}>Send RFQ</button></form>}</Card>)}</Block>
 <Block title="Supplier RFQs and price comparison">{d.rfqs.map(r=><Card row={r} key={r.id}>{r.status==="SENT"&&<ResponseForm row={r} suppliers={d.suppliers}/>}<div className="mt-3 grid gap-2 sm:grid-cols-2">{arr<Row>(r.responses).map(s=><div className="rounded-xl border p-3" key={s.id}><b>{String((s.supplier as {name?:string})?.name??s.reference)}</b><Badge v={s.status}/>{s.status==="SUBMITTED"&&<form action={createPoAction} className="mt-2 grid gap-2"><input type="hidden" name="id" value={s.id}/><Field name="expectedAt" title="Expected" type="date"/><Field name="paymentTerms" title="Terms" value="To be confirmed"/><button className={button}>Create PO</button></form>}</div>)}</div></Card>)}</Block>
 <Block title="Purchase orders and receipts">{d.purchaseOrders.map(r=><Card row={r} key={r.id}>{r.status==="PENDING_APPROVAL"&&<Decision action={decidePoAction} id={r.id}/>} {r.status==="APPROVED"&&<Simple action={sendPoAction} id={r.id} text="Send PO"/>}{["SENT","PARTIALLY_RECEIVED"].includes(r.status)&&<GrnForm row={r}/>}</Card>)}{d.receipts.map(r=><Card row={r} key={r.id}>{r.status==="DRAFT"&&<Simple action={postGrnAction} id={r.id} text="Post receipt to stock"/>}</Card>)}</Block>
 <Block title="Picking, dispatch and proof of delivery">{d.salesOrders.map(r=><Card row={r} key={r.id}>{arr<{id:string;fulfilmentLocationId:string;quantity:number;reservation?:{status:string};variant?:{product?:{name:string}}}>(r.items).some(i=>i.reservation?.status==="ACTIVE")&&<form action={createPickingAction}><input type="hidden" name="id" value={r.id}/><input type="hidden" name="locationId" value={arr<{fulfilmentLocationId:string;reservation?:{status:string}}>(r.items).find(i=>i.reservation?.status==="ACTIVE")?.fulfilmentLocationId}/><button className={button}>Create picking list</button></form>}{["DISPATCHED","DELIVERED","RETURNED"].includes(r.status)&&<ReturnForm row={r}/>}</Card>)}{d.pickingLists.map(r=><Card row={r} key={r.id}><DispatchForm row={r}/></Card>)}{d.dispatches.map(r=><Card row={r} key={r.id}>{r.status==="DRAFT"&&<Simple action={postDispatchAction} id={r.id} text="Dispatch reserved stock"/>}{r.status==="DISPATCHED"&&<form action={deliverAction} className="mt-3 grid gap-2 sm:grid-cols-3"><input type="hidden" name="id" value={r.id}/><Field name="receivedBy" title="Received by"/><Field name="receivedAt" title="Delivered at" type="datetime-local"/><button className={`${button} self-end`}>Record POD</button></form>}</Card>)}</Block>
 <Block title="Returns, quarantine and resolution">{d.returns.map(r=><Card row={r} key={r.id}>{r.status==="REQUESTED"&&<Simple action={approveReturnAction} id={r.id} text="Approve return"/>}{r.status==="APPROVED"&&<ReceiveReturn row={r}/>} {r.status==="RECEIVED"&&<InspectReturn row={r}/>}</Card>)}</Block>
 </main>
}
function Block({title,children}:{title:string;children:React.ReactNode}){return <section><h2 className="mb-3 text-2xl font-bold">{title}</h2><div className="space-y-3">{children}</div></section>}
function Card({row,children}:{row:Row;children:React.ReactNode}){return <details className={panel}><summary className="flex cursor-pointer justify-between gap-3"><b>{row.reference}</b><Badge v={row.status}/></summary><p className="mt-3 text-sm text-slate-600">{arr<Record<string,unknown>>(row.items).map(i=>String((i.variant as {product?:{name?:string}})?.product?.name??"Item")).join(" • ")||"Open for workflow actions"}</p>{children}</details>}
function Simple({action,id,text}:{action:(x:FormData)=>Promise<void>;id:string;text:string}){return <form action={action} className="mt-3"><input type="hidden" name="id" value={id}/><button className={button}>{text}</button></form>}
function Decision({action,id}:{action:(x:FormData)=>Promise<void>;id:string}){return <form action={action} className="mt-3 flex gap-2"><input type="hidden" name="id" value={id}/><input type="hidden" name="reason" value="Approved after operational review"/><button className={button} name="approve" value="true">Approve</button><button className="rounded-xl border px-4 text-red-700" name="approve" value="false">Reject</button></form>}
function ResponseForm({row,suppliers}:{row:Row;suppliers:Option[]}){const items=arr<{id:string;quantity:number}>(row.items);return <form action={addResponseAction} className="mt-3 grid gap-2 sm:grid-cols-2"><input type="hidden" name="id" value={row.id}/><label className={label}>Supplier<select className={input} name="supplierId">{suppliers.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><Field name="validUntil" title="Valid until" type="datetime-local"/><Field name="freightTotal" title="Freight" type="number" value={0}/>{items.map(i=><span key={i.id}><input type="hidden" name="rfqItemId" value={i.id}/><input type="hidden" name={`quantity_${i.id}`} value={i.quantity}/><Field name={`cost_${i.id}`} title="Unit cost" type="number" value={0}/><input type="hidden" name={`gst_${i.id}`} value="18"/><input type="hidden" name={`lead_${i.id}`} value="2"/></span>)}<button className={button}>Record response</button></form>}
function GrnForm({row}:{row:Row}){const items=arr<{id:string;orderedQuantity:number;receivedQuantity:number;targetLocationId:string}>(row.items);return <form action={createGrnAction} className="mt-3 grid gap-2"><input type="hidden" name="id" value={row.id}/><input type="hidden" name="locationId" value={items[0]?.targetLocationId}/><Field name="receivedAt" title="Received at" type="datetime-local"/>{items.map(i=>{const n=Math.max(1,i.orderedQuantity-i.receivedQuantity);return <span key={i.id}><input type="hidden" name="poItemId" value={i.id}/><input type="hidden" name={`received_${i.id}`} value={n}/><input type="hidden" name={`accepted_${i.id}`} value={n}/><input type="hidden" name={`rejected_${i.id}`} value="0"/><input type="hidden" name={`damaged_${i.id}`} value="0"/></span>})}<button className={button}>Create draft GRN</button></form>}
function DispatchForm({row}:{row:Row}){const items=arr<{salesOrderItemId:string;pickedQuantity:number}>(row.items);return <form action={createDispatchAction} className="mt-3"><input type="hidden" name="salesOrderId" value={String(row.salesOrderId)}/><input type="hidden" name="pickingListId" value={row.id}/>{items.map(i=><span key={i.salesOrderItemId}><input type="hidden" name="salesOrderItemId" value={i.salesOrderItemId}/><input type="hidden" name={`quantity_${i.salesOrderItemId}`} value={i.pickedQuantity}/></span>)}<button className={button}>Prepare dispatch and challan</button></form>}
function ReturnForm({row}:{row:Row}){const items=arr<{id:string}>(row.items);return <form action={createReturnAction} className="mt-3"><input type="hidden" name="id" value={row.id}/><input type="hidden" name="reason" value="Customer return request"/>{items.map(i=><span key={i.id}><input type="hidden" name="salesOrderItemId" value={i.id}/><input type="hidden" name={`quantity_${i.id}`} value="1"/></span>)}<button className={button}>Create return</button></form>}
function ReceiveReturn({row}:{row:Row}){const items=arr<{id:string;requestedQuantity:number}>(row.items);return <form action={receiveReturnAction}><input type="hidden" name="id" value={row.id}/>{items.map(i=><span key={i.id}><input type="hidden" name="returnItemId" value={i.id}/><input type="hidden" name={`quantity_${i.id}`} value={i.requestedQuantity}/></span>)}<button className={button}>Receive into quarantine</button></form>}
function InspectReturn({row}:{row:Row}){const items=arr<{id:string;receivedQuantity:number}>(row.items);return <form action={inspectReturnAction}><input type="hidden" name="id" value={row.id}/><input type="hidden" name="resolution" value="NONE"/>{items.map(i=><span key={i.id}><input type="hidden" name="returnItemId" value={i.id}/><input type="hidden" name={`decision_${i.id}`} value="RESTOCK"/><input type="hidden" name={`restock_${i.id}`} value={i.receivedQuantity}/><input type="hidden" name={`damaged_${i.id}`} value="0"/><input type="hidden" name={`rejected_${i.id}`} value="0"/></span>)}<button className={button}>Inspect and restock</button></form>}
