import Link from "next/link"
import { inventoryApiUrl, readApiError, requireStaffAccess } from "@/lib/staff-access"

type Summary={availableToPromise:number;lowStockItems:number;newQuotations:number;averageQuoteResponseHours:number|null;quoteConversionRate:number;openSalesOrders:number;delayedDispatches:number;pendingPurchaseOrders:number;pendingGoodsReceipts:number;expiringReservations:number;inventoryValuation:number;grossMargin:number|null}
type Dashboard={summary:Summary;warehouse:{name:string;physical:number;reserved:number;available:number}[];lowStock:{product:string;sku:string;location:string;available:number;threshold:number}[];reservations:{reference:string;product:string;location:string;quantity:number}[];purchaseOrders:{reference:string;supplier:string;status:string;total:string|number}[];supplierComparison:{rfq:string;supplier:string;total:number;averageLeadDays:number}[];supplierPerformance:{supplier:string;purchaseOrder:string;receivedAt:string;onTime:boolean}[];canViewMargin:boolean}
const panel="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"
const money=(value:number)=>`INR ${value.toLocaleString("en-IN",{maximumFractionDigits:0})}`

export default async function DashboardPage(){
  const {accessToken}=await requireStaffAccess("/dashboard")
  const response=await fetch(`${inventoryApiUrl}/fulfilment-operations/dashboard`,{headers:{Authorization:`Bearer ${accessToken}`},cache:"no-store"})
  if(!response.ok)throw new Error(await readApiError(response))
  const data=await response.json() as Dashboard
  const metrics:[string,string|number,string][]=[
    ["Available to promise",data.summary.availableToPromise,"/inventory-locations"],["Low-stock items",data.summary.lowStockItems,"/inventory-locations"],["New quotations",data.summary.newQuotations,"/quotations"],["Open sales orders",data.summary.openSalesOrders,"/fulfilment"],["Pending purchase orders",data.summary.pendingPurchaseOrders,"/fulfilment"],["Pending goods receipts",data.summary.pendingGoodsReceipts,"/fulfilment"],["Quote conversion",`${data.summary.quoteConversionRate.toFixed(1)}%`,"/quotations"],["Average quote response",data.summary.averageQuoteResponseHours===null?"No data":`${data.summary.averageQuoteResponseHours.toFixed(1)} h`,"/quotations"],["Expiring reservations",data.summary.expiringReservations,"/inventory-locations"],["Delayed dispatches",data.summary.delayedDispatches,"/fulfilment"],["Inventory valuation",money(data.summary.inventoryValuation),"/reports"],
  ]
  if(data.canViewMargin&&data.summary.grossMargin!==null)metrics.push(["Authorized gross margin",money(data.summary.grossMargin),"/reports"])
  const workspaces:[string,string][]=[["Catalogue","/catalog-control"],["Product Categories","/category-management"],["Know Your Material","/material-knowledge"],["Inventory","/inventory-locations"],["Quotations","/quotations"],["Purchasing and delivery","/fulfilment"],["Homepage","/homepage-content"],["Professionals","/professionals"],["Reports","/reports"]]
  return <main className="mx-auto w-full min-w-0 max-w-[1500px] space-y-8 overflow-x-hidden px-4 py-8 sm:px-6 lg:px-8">
    <header><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-700">Operations overview</p><h1 className="mt-2 text-3xl font-bold sm:text-4xl">Buildanta control centre</h1><p className="mt-2 text-slate-600">Live catalogue, stock, quotation, purchasing and delivery signals from the Inventory API.</p></header>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{metrics.map(([label,value,href])=><Link href={href} className={`${panel} min-w-0 transition hover:-translate-y-0.5 hover:border-emerald-300`} key={label}><p className="text-sm text-slate-500">{label}</p><p className="mt-2 break-words text-2xl font-bold">{value}</p></Link>)}</section>
    <section className="grid min-w-0 gap-6 lg:grid-cols-2"><Table title="Stock by warehouse" headers={["Location","Physical","Reserved","ATP"]} rows={data.warehouse.map(x=>[x.name,x.physical,x.reserved,x.available])}/><Table title="Low-stock attention" headers={["Product","Location","Available","Threshold"]} rows={data.lowStock.map(x=>[`${x.product} / ${x.sku}`,x.location,x.available,x.threshold])}/><Table title="Pending reservations" headers={["Reference","Product","Location","Quantity"]} rows={data.reservations.map(x=>[x.reference,x.product,x.location,x.quantity])}/><Table title="Purchase-order pipeline" headers={["PO","Supplier","Status","Value"]} rows={data.purchaseOrders.map(x=>[x.reference,x.supplier,x.status,money(Number(x.total))])}/><Table title="Supplier price comparison" headers={["RFQ","Supplier","Offered total","Lead"]} rows={data.supplierComparison.map(x=>[x.rfq,x.supplier,money(x.total),`${x.averageLeadDays.toFixed(1)} days`])}/><Table title="Supplier delivery performance" headers={["Supplier","PO","Received","On time"]} rows={data.supplierPerformance.map(x=>[x.supplier,x.purchaseOrder,new Date(x.receivedAt).toLocaleDateString("en-IN"),x.onTime?"Yes":"No"])}/></section>
    <section className={`${panel} min-w-0`}><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Operational workspaces</h2><p className="text-sm text-slate-500">Every link opens a working route.</p></div><div className="flex flex-wrap gap-2">{workspaces.map(([label,href])=><Link className="rounded-xl border border-slate-200 px-3 py-2 text-sm font-semibold hover:border-emerald-400" href={href} key={label}>{label}</Link>)}</div></div></section>
  </main>
}

function Table({title,headers,rows}:{title:string;headers:string[];rows:(string|number)[][]}){return <section className={`${panel} min-w-0 overflow-hidden`}><h2 className="text-xl font-bold">{title}</h2>{rows.length?<div className="mt-4 max-w-full overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="text-xs uppercase text-slate-500"><tr>{headers.map(header=><th className="whitespace-nowrap px-3 py-2" key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr className="border-t" key={index}>{row.map((value,column)=><td className={`whitespace-nowrap px-3 py-3 ${column===0?"sticky left-0 bg-white font-semibold":""}`} key={column}>{value}</td>)}</tr>)}</tbody></table></div>:<p className="mt-4 rounded-xl bg-slate-50 p-4 text-sm text-slate-500">No records need attention.</p>}</section>}
