import { FulfilmentMode, InventoryLedgerType, InventoryReservationStatus, StockCountStatus, StockTransferStatus } from "@workspace/db"
import { inventoryApiUrl, readApiError, requireStaffAccess } from "@/lib/staff-access"
import {
  adjustLocationBalanceAction,
  addPincodesAction,
  createCarrierAction,
  createCarrierServiceAreaAction,
  createDealerAction,
  createDealerProductAction,
  createDealerServiceAreaAction,
  createReservationAction,
  createServiceAreaAction,
  createStockCountAction,
  createSupplierProductAction,
  createTransferAction,
  createWarehouseAction,
  createWarehouseLocationAction,
  createUnitAction,
  createUnitConversionAction,
  linkServiceAreaAction,
  releaseReservationAction,
  transitionStockCountAction,
  transitionTransferAction,
} from "./actions"

type Warehouse = { id: string; code: string; name: string; city: string; pincode: string; active: boolean; locations: { id: string; code: string; name: string }[]; fulfilmentLocation: { id: string } | null }
type ServiceArea = { id: string; code: string; name: string; city: string; state: string; pincodes: { pincode: string }[] }
type Location = { id: string; code: string; name: string; type: string; mode: string; serviceAreas: { estimatedLeadDays: number; serviceArea: { name: string } }[] }
type Variant = { id: string; sku: string; unit: string; product: { name: string; brand: { name: string } } }
type Balance = { id: string; physicalQuantity: number; reservedQuantity: number; blockedQuantity: number; damagedQuantity: number; quarantineQuantity: number; inTransitQuantity: number; lowStockThreshold: number; availableQuantity: number; variant: Variant; fulfilmentLocation: { id: string; name: string }; warehouseLocation: { id: string; name: string } | null }
type Reservation = { id: string; reference: string; quantity: number; status: InventoryReservationStatus; expiresAt: string | null; variant: { sku: string; product: { name: string } }; fulfilmentLocation: { name: string } }
type Transfer = { id: string; reference: string; status: StockTransferStatus; originLocation: { name: string }; destinationLocation: { name: string }; items: { quantity: number; variant: { sku: string; product: { name: string } } }[] }
type StockCount = { id: string; reference: string; status: StockCountStatus; fulfilmentLocation: { name: string }; items: { expectedQuantity: number; countedQuantity: number; variant: { sku: string; product: { name: string } } }[] }
type Supplier = { id: string; name: string }
type Dealer = { id: string; code: string; name: string; city: string; products: unknown[] }
type Carrier = { id: string; code: string; name: string }
type Unit = { id: string; code: string; name: string; symbol: string; dimension: string | null; conversionsFrom: { id: string; multiplier: string; toUnit: { name: string; symbol: string } }[] }
type Ledger = { id: string; type: InventoryLedgerType; physicalDelta: number; reservedDelta: number; blockedDelta: number; damagedDelta: number; quarantineDelta: number; reason: string; reference: string | null; createdAt: string; balance: { variant: { sku: string; product: { name: string } }; fulfilmentLocation: { name: string } }; actor: { email: string } | null }
type Overview = { warehouses: Warehouse[]; serviceAreas: ServiceArea[]; fulfilmentLocations: Location[]; balances: Balance[]; reservations: Reservation[]; transfers: Transfer[]; stockCounts: StockCount[]; suppliers: Supplier[]; variants: Variant[]; dealers: Dealer[]; carriers: Carrier[]; units: Unit[]; recentLedger: Ledger[] }

const input = "mt-1.5 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none transition focus:border-emerald-600 focus:ring-2 focus:ring-emerald-100"
const textarea = "mt-1.5 min-h-24 w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm outline-none transition focus:border-emerald-600 focus:ring-2 focus:ring-emerald-100"
const button = "h-11 rounded-xl bg-[#0a2540] px-5 text-sm font-semibold text-white transition hover:bg-emerald-700"
const label = "text-sm font-medium text-slate-700"
const panel = "rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"

function optionLabel(variant: Variant) { return `${variant.product.name} / ${variant.sku}` }
function signed(value: number) { return value > 0 ? `+${value}` : String(value) }
function statusClass(status: string) { return status === "ACTIVE" || status === "RECEIVED" || status === "APPROVED" ? "bg-emerald-100 text-emerald-800" : status === "CANCELLED" || status === "RELEASED" ? "bg-slate-100 text-slate-600" : "bg-orange-100 text-orange-800" }

export default async function InventoryLocationsPage({ searchParams }: { searchParams: Promise<{ error?: string; saved?: string }> }) {
  const { accessToken } = await requireStaffAccess("/inventory-locations")
  const response = await fetch(`${inventoryApiUrl}/inventory-locations/overview`, { headers: { Authorization: `Bearer ${accessToken}` }, cache: "no-store" })
  if (!response.ok) throw new Error(await readApiError(response))
  const data = await response.json() as Overview
  const query = await searchParams
  const available = data.balances.reduce((sum, item) => sum + item.availableQuantity, 0)
  const unavailable = data.balances.reduce((sum, item) => sum + item.blockedQuantity + item.damagedQuantity + item.quarantineQuantity, 0)

  return <main className="mx-auto w-full max-w-[1500px] flex-1 space-y-8 px-4 py-8 sm:px-6 lg:px-8">
    <section className="overflow-hidden rounded-3xl bg-[#0a2540] p-6 text-white shadow-xl sm:p-8">
      <p className="text-xs font-semibold uppercase tracking-[0.18em] text-orange-300">Location-aware inventory</p>
      <div className="mt-3 grid gap-6 xl:grid-cols-[1fr_auto] xl:items-end"><div><h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Stock, serviceability and fulfilment</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-300">Manage where stock is held, which PIN codes can be served, what is genuinely available, and every reservation or movement behind the customer-safe storefront status.</p></div>
        <div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><Kpi value={data.warehouses.length} label="Warehouses"/><Kpi value={data.serviceAreas.length} label="Service areas"/><Kpi value={available} label="Available"/><Kpi value={unavailable} label="Controlled" warning/></div></div>
    </section>

    {query.error && <p role="alert" className="rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{query.error}</p>}
    {query.saved && <p role="status" className="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">Inventory operation saved and connected data refreshed.</p>}

    <section className="grid gap-5 xl:grid-cols-3">
      <details open className={panel}><summary className="cursor-pointer text-lg font-bold">Add warehouse</summary><form action={createWarehouseAction} className="mt-5 grid gap-3 sm:grid-cols-2"><Field name="code" title="Code" placeholder="KANPUR-WH1"/><Field name="name" title="Warehouse name" placeholder="Kanpur central yard"/><Field name="city" title="City" defaultValue="Kanpur"/><Field name="state" title="State" defaultValue="Uttar Pradesh"/><Field name="pincode" title="PIN code" pattern="[0-9]{6}"/><Field name="address" title="Address"/><Field name="locationCode" title="First bin code" defaultValue="MAIN"/><Field name="locationName" title="First bin name" defaultValue="Main storage"/><button className={`${button} sm:col-span-2`}>Create warehouse and fulfilment location</button></form></details>
      <details open className={panel}><summary className="cursor-pointer text-lg font-bold">Add service area</summary><form action={createServiceAreaAction} className="mt-5 grid gap-3 sm:grid-cols-2"><Field name="code" title="Code" placeholder="KANPUR-CENTRAL"/><Field name="name" title="Area name" placeholder="Kanpur Central"/><Field name="city" title="City" defaultValue="Kanpur"/><Field name="state" title="State" defaultValue="Uttar Pradesh"/><label className={`${label} sm:col-span-2`}>PIN codes<textarea name="pincodes" required placeholder="208001, 208002, 208003" className={textarea}/></label><button className={`${button} sm:col-span-2`}>Create service area</button></form></details>
      <details open className={panel}><summary className="cursor-pointer text-lg font-bold">Connect delivery coverage</summary><form action={linkServiceAreaAction} className="mt-5 grid gap-3"><Select name="fulfilmentLocationId" title="Fulfilment location" options={data.fulfilmentLocations.map((item) => [item.id, item.name])}/><Select name="serviceAreaId" title="Service area" options={data.serviceAreas.map((item) => [item.id, `${item.name} (${item.pincodes.length} PINs)`])}/><div className="grid grid-cols-2 gap-3"><Field name="estimatedLeadDays" title="Lead days" type="number" min="0" defaultValue="2"/><Field name="deliveryCharge" title="Delivery charge" type="number" min="0" step="0.01"/></div><Field name="minimumOrderValue" title="Minimum order value" type="number" min="0" step="0.01"/><button className={button}>Save coverage</button></form></details>
    </section>

    <section><SectionTitle eyebrow="Foundation controls" title="Bins, PIN codes and controlled units"/><div className="grid gap-5 xl:grid-cols-3">
      <div className={panel}><h3 className="text-lg font-bold">Add warehouse bin</h3><p className="mt-1 text-sm text-slate-500">Create a named storage position inside an existing warehouse.</p><form action={createWarehouseLocationAction} className="mt-4 grid gap-3"><Select name="warehouseId" title="Warehouse" options={data.warehouses.map((item) => [item.id, item.name])}/><Field name="code" title="Bin code" placeholder="RACK-A1"/><Field name="name" title="Bin name" placeholder="Rack A / shelf 1"/><Field name="zone" title="Zone (optional)" required={false}/><button className={button}>Add bin</button></form></div>
      <div className={panel}><h3 className="text-lg font-bold">Extend a service area</h3><p className="mt-1 text-sm text-slate-500">Add valid delivery PIN codes without recreating the area.</p><form action={addPincodesAction} className="mt-4 grid gap-3"><Select name="serviceAreaId" title="Service area" options={data.serviceAreas.map((item) => [item.id, item.name])}/><label className={label}>Additional PIN codes<textarea name="pincodes" required placeholder="208011, 208012" className={textarea}/></label><button className={button}>Add PIN codes</button></form></div>
      <div className={panel}><h3 className="text-lg font-bold">Controlled units</h3><form action={createUnitAction} className="mt-4 grid gap-3 sm:grid-cols-2"><Field name="code" title="Code" placeholder="BAG"/><Field name="symbol" title="Symbol" placeholder="bag"/><Field name="name" title="Unit name" placeholder="Bag"/><Field name="dimension" title="Dimension (optional)" placeholder="mass" required={false}/><button className={`${button} sm:col-span-2`}>Create unit</button></form>{data.units.length > 1 && <form action={createUnitConversionAction} className="mt-5 grid gap-3 border-t border-slate-100 pt-5"><Select name="fromUnitId" title="From unit" options={data.units.map((item) => [item.id, `${item.name} (${item.symbol})`])}/><Select name="toUnitId" title="To unit" options={data.units.map((item) => [item.id, `${item.name} (${item.symbol})`])}/><Field name="multiplier" title="Multiplier" type="number" min="0.000001" step="0.000001"/><button className={button}>Save conversion</button></form>}<div className="mt-5 flex flex-wrap gap-2">{data.units.map((item) => <span key={item.id} className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-700">{item.name} / {item.symbol}</span>)}</div></div>
    </div></section>

    <section className={panel}><div className="flex flex-col justify-between gap-4 lg:flex-row"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-emerald-700">Balances</p><h2 className="text-2xl font-bold tracking-tight">Adjust one location balance</h2><p className="mt-1 text-sm text-slate-500">Available = physical - reserved - blocked - damaged - quarantine.</p></div></div>
      <form action={adjustLocationBalanceAction} className="mt-5 grid gap-3 md:grid-cols-3 xl:grid-cols-6"><Select name="variantId" title="Product variant" options={data.variants.map((item) => [item.id, optionLabel(item)])} className="md:col-span-2"/><Select name="fulfilmentLocationId" title="Location" options={data.fulfilmentLocations.map((item) => [item.id, item.name])}/><Select name="type" title="Reason type" options={Object.values(InventoryLedgerType).map((item) => [item, item.replaceAll("_", " ")])}/><Field name="reference" title="Reference" placeholder="PO / quote / count"/><Field name="lowStockThreshold" title="Low-stock level" type="number" min="0"/>{["physicalDelta","reservedDelta","blockedDelta","damagedDelta","quarantineDelta","inTransitDelta"].map((name) => <Field key={name} name={name} title={name.replace("Delta", " change").replace(/([A-Z])/g, " $1")} type="number" defaultValue="0"/>)}<Field name="reason" title="Audit reason" placeholder="Why is this quantity changing?" className="md:col-span-2 xl:col-span-5"/><button className={`${button} self-end`}>Record change</button></form>
    </section>

    <section><SectionTitle eyebrow="Live operations" title="Balances by fulfilment location"/>{data.balances.length ? <div className="grid gap-4 lg:grid-cols-2 2xl:grid-cols-3">{data.balances.map((item) => <article key={item.id} className={panel}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-emerald-700">{item.fulfilmentLocation.name}</p><h3 className="mt-1 font-bold">{item.variant.product.name}</h3><p className="font-mono text-xs text-slate-500">{item.variant.sku}</p></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${item.availableQuantity <= item.lowStockThreshold ? "bg-orange-100 text-orange-800" : "bg-emerald-100 text-emerald-800"}`}>{item.availableQuantity} available</span></div><div className="mt-4 grid grid-cols-3 gap-2 rounded-2xl bg-slate-50 p-3 text-center text-sm"><Quantity value={item.physicalQuantity} label="Physical"/><Quantity value={item.reservedQuantity} label="Reserved"/><Quantity value={item.blockedQuantity} label="Blocked"/><Quantity value={item.damagedQuantity} label="Damaged"/><Quantity value={item.quarantineQuantity} label="Quarantine"/><Quantity value={item.inTransitQuantity} label="In transit"/></div></article>)}</div> : <Empty text="No location balances exist yet. Add a warehouse and record the first balance."/>}</section>

    <section className="grid gap-5 xl:grid-cols-3">
      <div className={panel}><h2 className="text-xl font-bold">Reserve stock</h2><form action={createReservationAction} className="mt-4 grid gap-3"><Field name="reference" title="Reservation reference" placeholder="QUOTE-1001"/><Select name="variantId" title="Variant" options={data.variants.map((item) => [item.id, optionLabel(item)])}/><Select name="fulfilmentLocationId" title="Location" options={data.fulfilmentLocations.map((item) => [item.id, item.name])}/><Field name="quantity" title="Quantity" type="number" min="1"/><Field name="expiresAt" title="Expires at" type="datetime-local"/><Field name="notes" title="Notes"/><button className={button}>Create reservation</button></form></div>
      <div className={panel}><h2 className="text-xl font-bold">Create stock transfer</h2><form action={createTransferAction} className="mt-4 grid gap-3"><Field name="reference" title="Transfer reference" placeholder="TR-1001"/><Select name="originLocationId" title="Origin" options={data.fulfilmentLocations.map((item) => [item.id, item.name])}/><Select name="destinationLocationId" title="Destination" options={data.fulfilmentLocations.map((item) => [item.id, item.name])}/><Select name="variantId" title="Variant" options={data.variants.map((item) => [item.id, optionLabel(item)])}/><Field name="quantity" title="Quantity" type="number" min="1"/><Field name="notes" title="Notes"/><button className={button}>Create draft transfer</button></form></div>
      <div className={panel}><h2 className="text-xl font-bold">Record stock count</h2><form action={createStockCountAction} className="mt-4 grid gap-3"><Field name="reference" title="Count reference" placeholder="COUNT-1001"/><Select name="fulfilmentLocationId" title="Location" options={data.fulfilmentLocations.map((item) => [item.id, item.name])}/><Select name="variantId" title="Variant" options={data.variants.map((item) => [item.id, optionLabel(item)])}/><Field name="countedQuantity" title="Counted physical quantity" type="number" min="0"/><Field name="notes" title="Notes"/><button className={button}>Create draft count</button></form></div>
    </section>

    <section className="grid gap-6 2xl:grid-cols-2"><WorkflowTable title="Reservations" empty="No reservations yet.">{data.reservations.map((item) => <article key={item.id} className="flex flex-col gap-3 border-b border-slate-100 py-4 last:border-0 sm:flex-row sm:items-center sm:justify-between"><div><b>{item.reference} / {item.variant.product.name}</b><p className="text-sm text-slate-500">{item.quantity} at {item.fulfilmentLocation.name}</p></div><div className="flex items-center gap-2"><Status value={item.status}/>{item.status === InventoryReservationStatus.ACTIVE && <form action={releaseReservationAction}><input type="hidden" name="id" value={item.id}/><button className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold hover:bg-slate-50">Release</button></form>}</div></article>)}</WorkflowTable>
      <WorkflowTable title="Transfers" empty="No transfers yet.">{data.transfers.map((item) => <article key={item.id} className="border-b border-slate-100 py-4 last:border-0"><div className="flex flex-col justify-between gap-2 sm:flex-row"><div><b>{item.reference}: {item.originLocation.name} to {item.destinationLocation.name}</b><p className="text-sm text-slate-500">{item.items.map((line) => `${line.variant.product.name} x ${line.quantity}`).join(", ")}</p></div><Status value={item.status}/></div>{item.status === StockTransferStatus.DRAFT && <TransitionForm action={transitionTransferAction} id={item.id} status={StockTransferStatus.IN_TRANSIT} label="Dispatch"/>}{item.status === StockTransferStatus.IN_TRANSIT && <TransitionForm action={transitionTransferAction} id={item.id} status={StockTransferStatus.RECEIVED} label="Receive"/>}</article>)}</WorkflowTable>
      <WorkflowTable title="Stock counts" empty="No stock counts yet.">{data.stockCounts.map((item) => <article key={item.id} className="border-b border-slate-100 py-4 last:border-0"><div className="flex justify-between gap-3"><div><b>{item.reference} / {item.fulfilmentLocation.name}</b><p className="text-sm text-slate-500">{item.items.map((line) => `${line.variant.product.name}: ${line.expectedQuantity} to ${line.countedQuantity}`).join(", ")}</p></div><Status value={item.status}/></div>{item.status === StockCountStatus.DRAFT && <TransitionForm action={transitionStockCountAction} id={item.id} status={StockCountStatus.SUBMITTED} label="Submit count"/>}{item.status === StockCountStatus.SUBMITTED && <TransitionForm action={transitionStockCountAction} id={item.id} status={StockCountStatus.APPROVED} label="Approve and post"/>}</article>)}</WorkflowTable>
      <WorkflowTable title="Recent inventory ledger" empty="No ledger entries yet.">{data.recentLedger.map((item) => <article key={item.id} className="border-b border-slate-100 py-4 last:border-0"><div className="flex flex-col justify-between gap-2 sm:flex-row"><div><b>{item.balance.variant.product.name} / {item.balance.fulfilmentLocation.name}</b><p className="text-sm text-slate-500">{item.type.replaceAll("_", " ")} / {item.reason}</p><p className="font-mono text-xs text-slate-400">{item.reference || "No reference"} / {new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(item.createdAt))}</p></div><span className="text-right text-xs font-semibold text-slate-600">Physical {signed(item.physicalDelta)}<br/>Reserved {signed(item.reservedDelta)}<br/>Controlled {signed(item.blockedDelta + item.damagedDelta + item.quarantineDelta)}</span></div></article>)}</WorkflowTable></section>

    <section><SectionTitle eyebrow="Supply network" title="Supplier, dealer and carrier records"/><div className="grid gap-5 xl:grid-cols-3"><div className={panel}><h3 className="text-lg font-bold">Supplier product terms</h3><form action={createSupplierProductAction} className="mt-4 grid gap-3"><Select name="supplierId" title="Supplier" options={data.suppliers.map((item) => [item.id, item.name])}/><Select name="variantId" title="Variant" options={data.variants.map((item) => [item.id, optionLabel(item)])}/><Select name="fulfilmentMode" title="Mode" options={Object.values(FulfilmentMode).map((item) => [item, item.replaceAll("_", " ")])}/><Field name="supplierSku" title="Supplier SKU (optional)" required={false}/><div className="grid grid-cols-2 gap-3"><Field name="price" title="Current price (optional)" type="number" min="0" step="0.01" required={false}/><Field name="minimumQuantity" title="Minimum quantity" type="number" min="1" defaultValue="1"/></div><div className="grid grid-cols-2 gap-3"><Field name="minimumDays" title="Min lead days (optional)" type="number" min="0" required={false}/><Field name="maximumDays" title="Max lead days (optional)" type="number" min="0" required={false}/></div><Select name="serviceAreaId" title="Lead-time area (optional)" options={data.serviceAreas.map((item) => [item.id, item.name])} optional/><button className={button}>Save supplier terms</button></form></div>
      <div className={panel}><h3 className="text-lg font-bold">Dealer / fulfilment partner</h3><form action={createDealerAction} className="mt-4 grid gap-3 sm:grid-cols-2"><Field name="code" title="Code"/><Field name="name" title="Name"/><Field name="city" title="City"/><Field name="state" title="State"/><Field name="pincode" title="PIN code" pattern="[0-9]{6}"/><Field name="phone" title="Phone"/><Field name="email" title="Email" type="email" className="sm:col-span-2"/><Field name="address" title="Address" className="sm:col-span-2"/><button className={`${button} sm:col-span-2`}>Create dealer</button></form>{data.dealers.length > 0 && <form action={createDealerProductAction} className="mt-6 grid gap-3 border-t border-slate-100 pt-5"><Select name="dealerId" title="Dealer" options={data.dealers.map((item) => [item.id, item.name])}/><Select name="variantId" title="Variant" options={data.variants.map((item) => [item.id, optionLabel(item)])}/><div className="grid grid-cols-3 gap-3"><Field name="price" title="Price" type="number" min="0" step="0.01"/><Field name="reportedQuantity" title="Reported qty" type="number" min="0"/><Field name="leadTimeDays" title="Lead days" type="number" min="0" defaultValue="2"/></div><button className={button}>Confirm dealer product</button></form>}</div>
      <div className={panel}><h3 className="text-lg font-bold">Transport partner</h3><form action={createCarrierAction} className="mt-4 grid gap-3"><Field name="code" title="Code"/><Field name="name" title="Carrier name"/><Field name="phone" title="Phone"/><Field name="email" title="Email" type="email"/><button className={button}>Create carrier</button></form><div className="mt-6 space-y-2 border-t border-slate-100 pt-5">{data.carriers.map((item) => <p key={item.id} className="rounded-xl bg-slate-50 px-3 py-2 text-sm"><b>{item.name}</b><span className="ml-2 font-mono text-xs text-slate-500">{item.code}</span></p>)}{!data.carriers.length && <p className="text-sm text-slate-500">No transport partners yet.</p>}</div></div></div></section>

    <section><SectionTitle eyebrow="Service assignments" title="Connect partners to delivery areas"/><div className="grid gap-5 lg:grid-cols-2">
      <div className={panel}><h3 className="text-lg font-bold">Dealer coverage</h3><form action={createDealerServiceAreaAction} className="mt-4 grid gap-3 sm:grid-cols-2"><Select name="dealerId" title="Dealer" options={data.dealers.map((item) => [item.id, item.name])}/><Select name="serviceAreaId" title="Service area" options={data.serviceAreas.map((item) => [item.id, item.name])}/><Field name="deliveryCharge" title="Delivery charge (optional)" type="number" min="0" step="0.01" required={false}/><Field name="minimumOrderValue" title="Minimum order (optional)" type="number" min="0" step="0.01" required={false}/><Field name="estimatedLeadDays" title="Lead days" type="number" min="0" defaultValue="2"/><button className={`${button} self-end`}>Save dealer coverage</button></form></div>
      <div className={panel}><h3 className="text-lg font-bold">Carrier coverage</h3><form action={createCarrierServiceAreaAction} className="mt-4 grid gap-3 sm:grid-cols-2"><Select name="carrierId" title="Carrier" options={data.carriers.map((item) => [item.id, item.name])}/><Select name="serviceAreaId" title="Service area" options={data.serviceAreas.map((item) => [item.id, item.name])}/><Field name="baseCharge" title="Base charge (optional)" type="number" min="0" step="0.01" required={false}/><Field name="perKmCharge" title="Per-km charge (optional)" type="number" min="0" step="0.01" required={false}/><button className={`${button} sm:col-span-2`}>Save carrier coverage</button></form></div>
    </div></section>
  </main>
}

function Kpi({ value, label: text, warning = false }: { value: number; label: string; warning?: boolean }) { return <span className={`rounded-2xl px-4 py-3 ${warning ? "bg-orange-400/15" : "bg-white/10"}`}><b className="block text-2xl">{value}</b><small className={warning ? "text-orange-100" : "text-slate-300"}>{text}</small></span> }
const optionalFieldNames = new Set(["address", "phone", "email", "notes", "reference", "expiresAt", "lowStockThreshold", "deliveryCharge", "minimumOrderValue", "supplierSku", "price", "reportedQuantity", "minimumDays", "maximumDays", "baseCharge", "perKmCharge", "zone", "dimension"])
function Field({ name, title, className = "", required, ...props }: { name: string; title: string; className?: string } & React.InputHTMLAttributes<HTMLInputElement>) { return <label className={`${label} ${className}`}>{title}<input name={name} required={required ?? !optionalFieldNames.has(name)} className={input} {...props}/></label> }
function Select({ name, title, options, className = "", optional = false }: { name: string; title: string; options: [string, string][]; className?: string; optional?: boolean }) { return <label className={`${label} ${className}`}>{title}<select name={name} required={!optional} className={input}>{optional && <option value="">All areas</option>}{!optional && options.length === 0 && <option value="">No records available</option>}{options.map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select></label> }
function Quantity({ value, label: text }: { value: number; label: string }) { return <div><b className="block text-lg">{value}</b><small className="text-slate-500">{text}</small></div> }
function SectionTitle({ eyebrow, title }: { eyebrow: string; title: string }) { return <div className="mb-4"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-emerald-700">{eyebrow}</p><h2 className="text-2xl font-bold tracking-tight">{title}</h2></div> }
function Empty({ text }: { text: string }) { return <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-center text-sm text-slate-500">{text}</div> }
function Status({ value }: { value: string }) { return <span className={`h-fit rounded-full px-3 py-1 text-xs font-semibold ${statusClass(value)}`}>{value.replaceAll("_", " ")}</span> }
function WorkflowTable({ title, empty, children }: { title: string; empty: string; children: React.ReactNode[] }) { return <section className={panel}><h2 className="text-xl font-bold">{title}</h2><div className="mt-2">{children.length ? children : <p className="py-8 text-center text-sm text-slate-500">{empty}</p>}</div></section> }
function TransitionForm({ action, id, status, label: text }: { action: (formData: FormData) => Promise<void>; id: string; status: string; label: string }) { return <form action={action} className="mt-3"><input type="hidden" name="id" value={id}/><input type="hidden" name="status" value={status}/><button className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold hover:bg-slate-50">{text}</button></form> }
